server:
  port: 8765
  error:
    whitelabel:
      enabled: true

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

feign:
  hystrix:
    enabled: true

management:
  security:
    enabled: false

spring:
  application:
    name: eureka-feign