server:
  port: 8888

management:
  security:
    enabled: false

# 需要添加Spring Security
security:
  user:
    name: admin
    password: admin

spring:
  application:
    name: config-server
  cloud:
    config:
      lable: master
      server:
        git:
          uri: https://github.com/MrYang/springcloud.git
          searchPaths: cloud-config-repo
        #native:  本地查找
        #  searchLocations: /data/config-repo

    stream:
      kafka:
        binder:
          brokers: 127.0.0.1:9092
          zk-nodes: 127.0.0.1:2181