server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      lable: master
      server:
        git:
          uri: https://github.com/MrYang/springcloud.git
          searchPaths: cloud-config-repo